package com.pkware.micronaut.grpc.authorization

import io.grpc.BindableService
import io.grpc.ServerServiceDefinition
import io.micronaut.context.BeanContext
import io.micronaut.inject.BeanDefinition
import io.micronaut.inject.ExecutableMethod
import jakarta.inject.Singleton

/**
 * Builds a `fullMethodName → required-scopes` map at startup from
 * [jakarta.annotation.security.RolesAllowed] annotations on gRPC service methods.
 *
 * For each [BindableService], walks its gRPC [ServerServiceDefinition] to enumerate
 * method names, finds the matching [ExecutableMethod], and reads `@RolesAllowed` via
 * Micronaut's compile-time annotation metadata ([ExecutableMethod.stringValues]) — no
 * `java.lang.reflect`. Methods without `@RolesAllowed` are absent; absence means "deny"
 * in the interceptor's deny-by-default model.
 *
 *
 * The `@RolesAllowed → @Executable` metadata is generated by the `security-grpc-processor`
 * `RolesAllowedAnnotationMapper`, which must be on the consumer's annotation processor classpath.
 *
 * @param services all gRPC services registered in the application context.
 * @param beanContext for resolving each service's bean definition and executable-method metadata.
 */
@Singleton
public class GrpcScopeRegistry public constructor(
  services: MutableCollection<BindableService>,
  beanContext: BeanContext,
) {
  private val scopesByMethod: Map<String, Set<String>>

  init {
    val map = HashMap<String, MutableSet<String>>()
    for (service in services) {
      val beanDefinition: BeanDefinition<*> = beanContext.getBeanDefinition(service.javaClass)
      val serviceDefinition = service.bindService()
      for (grpcMethod in serviceDefinition.serviceDescriptor.methods) {
        val methodName: String = methodName(grpcMethod.fullMethodName)
        for (executableMethod in beanDefinition.getExecutableMethods()) {
          if (executableMethod.methodName == methodName) {
            val roles: Array<String> = executableMethod.stringValues(ROLES_ALLOWED)
            if (roles.isNotEmpty()) {
              map[grpcMethod.fullMethodName] = mutableSetOf(*roles)
            }
            break
          }
        }
      }
    }
    this.scopesByMethod = java.util.Map.copyOf<String, Set<String>>(map)
  }

  /**
   * Returns the scopes required to call the given gRPC method, or `null` if the method
   * carries no `@RolesAllowed` annotation (deny-by-default).
   */
  internal fun requiredScopes(fullMethodName: String): Set<String>? = scopesByMethod[fullMethodName]

  private companion object {
    private const val ROLES_ALLOWED: String = "jakarta.annotation.security.RolesAllowed"

    private fun methodName(fullMethodName: String): String {
      val slash = fullMethodName.lastIndexOf('/')
      return if (slash >= 0) fullMethodName.substring(slash + 1) else fullMethodName
    }
  }
}
