package com.pkware.micronaut.grpc.authorization;

import io.grpc.BindableService;
import io.grpc.MethodDescriptor;
import io.grpc.ServerServiceDefinition;
import io.micronaut.context.BeanContext;
import io.micronaut.inject.BeanDefinition;
import io.micronaut.inject.ExecutableMethod;
import jakarta.inject.Singleton;
import org.jspecify.annotations.Nullable;

import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;

/**
 * Builds a {@code fullMethodName → required-scopes} map at startup from
 * {@code jakarta.annotation.security.RolesAllowed} annotations on gRPC service methods.
 *
 * <p>For each {@link BindableService}, walks its gRPC {@link ServerServiceDefinition} to enumerate
 * method names, finds the matching {@link ExecutableMethod}, and reads {@code @RolesAllowed} via
 * Micronaut's compile-time annotation metadata ({@link ExecutableMethod#stringValues(String)}) — no
 * {@code java.lang.reflect}. Methods without {@code @RolesAllowed} are absent; absence means "deny"
 * in the interceptor's deny-by-default model.
 *
 * <p>The {@code @RolesAllowed → @Executable} metadata is generated by the {@code security-grpc-processor}
 * {@code RolesAllowedAnnotationMapper}, which must be on the consumer's annotation processor classpath.
 */
@Singleton
public final class GrpcScopeRegistry {

  static final String ROLES_ALLOWED = "jakarta.annotation.security.RolesAllowed";

  private final Map<String, Set<String>> scopesByMethod;

  /**
   * @param services all gRPC services registered in the application context.
   * @param beanContext for resolving each service's bean definition and executable-method metadata.
   */
  public GrpcScopeRegistry(Collection<BindableService> services, BeanContext beanContext) {
    var map = new HashMap<String, Set<String>>();
    for (var service : services) {
      BeanDefinition<?> beanDefinition = beanContext.getBeanDefinition(service.getClass());
      ServerServiceDefinition serviceDefinition = service.bindService();
      for (var grpcMethod : serviceDefinition.getServiceDescriptor().getMethods()) {
        String methodName = methodName(grpcMethod.getFullMethodName());
        for (var executableMethod : beanDefinition.getExecutableMethods()) {
          if (executableMethod.getMethodName().equals(methodName)) {
            String[] roles = executableMethod.stringValues(ROLES_ALLOWED);
            if (roles.length > 0) {
              map.put(grpcMethod.getFullMethodName(), Set.of(roles));
            }
            break;
          }
        }
      }
    }
    this.scopesByMethod = Map.copyOf(map);
  }

  /**
   * Returns the scopes required to call the given gRPC method, or {@code null} if the method
   * carries no {@code @RolesAllowed} annotation (deny-by-default).
   */
  public @Nullable Set<String> requiredScopes(String fullMethodName) {
    return scopesByMethod.get(fullMethodName);
  }

  private static String methodName(String fullMethodName) {
    int slash = fullMethodName.lastIndexOf('/');
    return slash >= 0 ? fullMethodName.substring(slash + 1) : fullMethodName;
  }
}
